version: "2"
run:
  concurrency: 4
  go: 1.25.6
  build-tags:
    - mytag
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  path-prefix: ""
linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - whitespace
  disable:
    - bodyclose
    - depguard
    - err113
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - lll
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gocognit
          - nlreturn
          - unparam
        path: include/
      - linters:
          - gosec
        path: settings/hmac/
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        source: '^//go:generate '
      - path: (.+)\.go$
        text: abcdef
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true
    cyclop:
      max-complexity: 10
      package-average: 0
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: false
      ignore-enum-members: ""
      package-scope-only: false
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: fmt\.Print.*
    funlen:
      lines: 80
      statements: 40
    gocognit:
      min-complexity: 10
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: false
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        underef:
          skipRecvDeref: true
    gocyclo:
      min-complexity: 10
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      enable:
        - atomicalign
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    importas:
      alias:
        - pkg: knative.dev/serving/pkg/apis/serving/v1
          alias: servingv1
        - pkg: knative.dev/serving/pkg/apis/autoscaling/v1alpha1
          alias: autoscalingv1alpha1
        - pkg: knative.dev/serving/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
      no-unaliased: true
    lll:
      line-length: 120
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
      ignore-rules:
        - someword
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 4
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    nlreturn:
      block-size: 1
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    promlinter:
      strict: false
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: true
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      ignore-names:
        - err
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
      ignore-chan-recv-ok: false
      ignore-decls:
        - t testing.T
        - ch chan<- prometheus.Metric
    whitespace:
      multi-if: false
      multi-func: false
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
      force-short-decl-cuddling: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/stackitcloud/external-dns-stackit-webhook)
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
